apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zkp-auth

resources:
  - server.yaml
  - client.yaml

images:
  - name: ghcr.io/pavelnikolov/zkpauth-server
    newName: ghcr.io/pavelnikolov/zkpauth-server
    newTag: latest
  - name: ghcr.io/pavelnikolov/zkpauth-client
    newName: ghcr.io/pavelnikolov/zkpauth-client
    newTag: latest
