apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client-ns.yaml
  - server-ns.yaml
  - server.yaml
  - client.yaml
  - server-svc.yaml

images:
  - name: ghcr.io/pavelnikolov/zkpauth-server
    newName: ghcr.io/pavelnikolov/zkpauth-server
    newTag: latest
  - name: ghcr.io/pavelnikolov/zkpauth-client
    newName: ghcr.io/pavelnikolov/zkpauth-client
    newTag: latest
